# Generated by Django 3.0.8 on 2020-07-26 11:42

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=42)),
                ('ram', models.CharField(max_length=12)),
                ('hd_capacity', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=42)),
                ('ram', models.CharField(max_length=12)),
                ('screen_size', models.CharField(max_length=24)),
                ('color', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=product.models.product_image_file_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
