# Generated by Django 3.0.8 on 2020-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200726_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('mobile', 'mobile'), ('laptop', 'laptop')], default='mobile', max_length=20),
        ),
    ]
